### ISSUE TITLE
Screen not being captured correctly

### ISSUE THREAD

**Issue by Benzlebug08** [BoboTiG/python-mss#25]
Hi
I've been trying to find a way to capture my Mac's screen to use to train a neural network, but I couldn't find a way to capture the screen with decent FPS until I found your library. The FPS using this library are very good, however the screen is not being captured correctly.

### General informations:

* OS name: _macOS_
* OS version: __10.12.5__
* OS architecture: _64 bits_
* Result of the command `python --version`: __Python 3.6.0 :: Anaconda custom (x86_64)__

For GNU/Linux users:

* Desktop Environment: _Quartz_

### Description of the warning/error

Using `grab()` to capture either the whole screen or a section of the screen, the display is not captured properly, looking like every other row of pixels has been shifted to the side. This happens when using OpenCV to show the image and when saving the image to a file. 

![screenshot](https://user-images.githubusercontent.com/11067128/29297067-4825a05e-8156-11e7-848a-de1690c803f5.jpg)
<img width="1280" alt="screen shot 2017-08-15 at 00 38 59" src="https://user-images.githubusercontent.com/11067128/29297140-c80ee942-8156-11e7-9dc5-9fa7cebbeafb.png">

#### Code (OpenCV/Numpy Example Code):

```
import time

import cv2
import mss
import numpy


with mss.mss() as sct:
    # Part of the screen to capture
    monitor = {'top': 50, 'left': 0, 'width': 840, 'height': 940}

    while 'Screen capturing':
        last_time = time.time()

        # Get raw pixels from the screen, save it to a Numpy array
        img = numpy.array(sct.grab(monitor))

        # Display the picture
        # cv2.resize(img, (40, 40))
        cv2.imshow('OpenCV/Numpy normal', img)

        # Display the picture in grayscale
        # cv2.imshow('OpenCV/Numpy grayscale',
       # cv2.cvtColor(img, cv2.COLOR_BGRA2GRAY))

        print('fps: {0}'.format(1 / (time.time()-last_time)))

        # Press "q" to quit
        if cv2.waitKey(25) & 0xFF == ord('q'):
            cv2.destroyAllWindows()
            break
```

I am using the dev branch as the [master branch does not work on Macs](https://github.com/BoboTiG/python-mss/issues/19).

### Full message

N/A

### Other details

This happens when capturing the whole screen and a section of the screen.

Thank You.

**Comment by BoboTiG** [comment]
Hello,

Thank you for the report. We are near to the resolution of that macOs specific bug :)
Could you retry with the updated dev branch?

**Comment by Benzlebug08** [comment]
Hi, 

Thanks for the quick reply :) I have installed the updated dev branch however the problem still persists.

**Comment by BoboTiG** [comment]
Hm.

1. What is the content of `sct.monitors`?
2. Using PIL ou direct save is always the same bad result?
3. If you try [those examples](https://python-mss.readthedocs.io/en/dev/examples.html#basics), all screenshots are bad? I am especially interested by the 1st and 3rd ones.
4. Do you have a specific display setup or something not usual that can help me?

**Comment by Benzlebug08** [comment]
Hi 
Sorry for not replying, but for some reason now it works fine. I'm still looking into what caused it, as I can't reproduce it again. 

Thanks for the help :)

**Comment by ScottehMax** [comment]
Hi there,

I'm experiencing this same issue. It's exclusive to the retina display on the MBP, as neither of the external monitors plugged in (not HiDPI) have any issue. Since retina displays are usually scaled down to a lower "apparent" resolution, it seems the detected width and height of the screenshot are the scaled down resolution, but the actual raw pixels are still the entire size of the display.

The content of `sct.monitors` is `[{'width': 4640, 'top': -160, 'height': 1184, 'left': 0}, {'width': 1440, 'top': 0, 'height': 900, 'left': 0}, {'width': 1280, 'top': 224, 'height': 800, 'left': 1440}, {'width': 1920, 'top': -160, 'height': 1080, 'left': 2720}]`

The monitor in question with issues is monitor 2, but the problem persists even if there are no external monitors plugged in. I'm using Python 2.7.14 and the current dev branch as of commit 96b18f698d33afeab9a73d62e91ffecb8663bdd9.

I've tried all of the examples, and as far as I'm aware, the problem continues throughout them for both grabbing a specific portion of the screen, and grabbing the full screen.

Something similar to the error message in #23 appears when using `sct.shot`: `ValueError: attempt to assign bytes of size 4096000 to extended slice of size 1024000`. 4096000 here is the "true" amount of pixels (2560 x 1600), while 1024000 is the scaled down "apparent" resolution (1280 x 800).

I was able to get the screenshot to display properly by hardcoding the dimensions of 2560 and 1600 in a couple places in screenshot.py, but of course the resulting image was not the desired size of 1280 x 800.

Any ideas what I can do to fix it so that it scales properly in the first place? Thanks for your time.

**Comment by cookiehunter22** [comment]
I have the same problem as both guys above. 
mss 3.1.0
MacBook Pro (Retina, Mid 2012). High Sierra 10.13.1
Quarz
Python 3.6.x
Anaconda

**Comment by dcrockwell** [comment]
This is still happening:

<img width="1807" alt="image" src="https://github.com/BoboTiG/python-mss/assets/53482/98ba0fa1-548a-4660-ad8c-3578f40f35c7">

**Comment by BoboTiG** [comment]
@dcrockwell Can you give lots more details please?

**Comment by dcrockwell** [comment]
I think I found the issue:

- `screen = sct.grab(bounding_box)` seems to grab `rgba` on MacOS Ventura 13.6
- To use `screen_array` in `yolov8` I have to first convert from `rgba` to `rgb`.
- I thought it was necessary to use `Image.frombytes` because of an example I found online, but this is what's corrupting the image.

So, this code works, but displays a distorted image:

```
screen = sct.grab(bounding_box)
    screen_array = np.array(screen)
    screen_color = cv2.cvtColor(screen_array, cv2.COLOR_RGBA2RGB)

    screen_image = Image.frombytes(
        'RGB', (bounding_box['width'], bounding_box['height']), screen_color)

    cv2.imshow('screen', np.array(screen_image))
```

This code works correctly without any distortion and correct color:

```
    screen = sct.grab(bounding_box)
    screen_array = np.array(screen)
    screen_color = cv2.cvtColor(screen_array, cv2.COLOR_RGBA2RGB)

    cv2.imshow('screen', screen_color)
```

I'm brand new to `mss` and `cv2`, so I have limited understanding of why the two code snippets work the way they do. Let me know if there's anything more I can do to help.
